# Site
title:       Volatile Vectors
bio:         'Virtual Reality Development, Spacial Computing & Interaction Design, Unity, C#'
description: "Virtual Reality Development, Spacial Computing & Interaction Design, Unity, C#"
locale:      en_US
baseurl: "/"
url:     "https://www.volatilevectors.de"

# Comments
disqus_shortname:   volatilevectors

# Social
# analytics-id:       "default"
twitter:   VolatileVectors
instagram: volatilevectors
github:    VolatileVectors

# personal
location: Berlin, GERMANY
phone:    +49-1577-890-4223
email:    contact@volatilevectors.de

# Other
background_image: /images/bg.jpg

# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you/

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout:    post
    author:    "Helge Backhaus"

# Jekyll
permalink:        /blog/:title/
markdown:         kramdown
highlighter:      rouge
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false
mathjax:          true
sass:
  sass_dir:       _sass
  style:          compressed

# Plugins
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
